### ISSUE TITLE
Details incomplete in your assignment submission

### ISSUE THREAD

**Issue by raven123** [Santhoshnmca/netsmobile#1]
1. Why 4 branches pushed into repository. Please mention which branch to be reviewed for Assignment. It will be better if you remove unwanted branches from the repository
2. I can see System.out.Print statement in your code which is not a good practice and one file only has that statement viz; App.java
3. I cannot see Readme.md file which states the steps to setup the environment for your framework and steps how to proceed with the setup and execute the test cases. Please include the same.
 Please fix above issues so that I can proceed further with review

**Comment by Santhoshnmca** [comment]
Hi Raven, 

Incorporated your comments and  please refer the Demo branch for assignment review.

Thanks,
Santhosh N

**Comment by Santhoshnmca** [comment]
closing the comment
